[package]
name = "enrgy"
version = "0.2.1"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

description = "A (nightly) insecure lightweight synchronous Actix-like HTTP server"
repository = "https://github.com/Txuritan/enrgy"

license = "MIT"

keywords = [ "synchronous", "http", "server", "nightly", "insecure" ]

[dependencies]
ctrlc = "3.1"
flate2 = "1.0"
form_urlencoded = "1.0"
log = "0.4"
path-tree = "0.1"
percent-encoding = "2.1"
