[package]
name = "enrgy"
version = "0.1.0"
authors = ["Txuritan <txuritan@protonmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "3.1"
form_urlencoded = "1.0"
path-tree = "0.1"
percent-encoding = "2.1"
qstring = "0.7"
